Repository VestaOfOrion/Vesta.Bay, pull requests merged in 2020-12, with the labels that each got.

#11 Fixes for Shells/Tajaran + Age tweaks for all species
  baystation12.dme
  code/__defines/culture.dm
  code/__defines/languages.dm
  code/modules/species/outsider/vox.dm
  code/modules/species/station/station.dm
  code/stylesheet.dm
  html/changelogs/purplepineapple-PR-11.yml
  modular_boh/code/modules/clothing/clothing.dm
  modular_boh/code/modules/clothing/spacesuit/void.dm
  modular_boh/code/modules/species/shell/shell.dm
  modular_mithra/code/modules/clothing/spacesuits/rig/suits/station.dm
  modular_mithra/code/modules/culture_descriptor/cultures_tajaran.dm
  modular_mithra/code/modules/mob/language/tajaran.dm
  modular_mithra/code/modules/organs/robolimbs.dm
  modular_mithra/code/modules/species/station/tajaran.dm
  modular_mithra/icons/mob/human_races/cyberlimbs/Jovian/jovian_main.dmi
  modular_mithra/icons/mob/human_races/cyberlimbs/zenghu/zenghumk2_main.dmi
  modular_mithra/icons/mob/human_races/cyberlimbs/zenghu/zenghumk3_main.dmi
Labels: Fix

#30 Dorch Adjustments
  html/changelogs/lamasmaster-PR-30.yml
  maps/torch/torch5_deck1.dmm
Labels: Map, Review Required 👓

#32 Add a pair of new hairstyles
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/human_races/species/human/hair.dmi
Labels: Feature, Review Required 👓

#33 Backgrounds, NCos, planets and culture fixes
  baystation12.dme
  code/__defines/culture.dm
  code/__defines/languages.dm
  code/modules/culture_descriptor/culture/cultures_human.dm
  code/modules/culture_descriptor/faction/factions_human.dm
  code/modules/culture_descriptor/location/locations_human.dm
  code/modules/mob/language/human/russian.dm
  code/modules/species/station/machine.dm
  code/modules/species/station/station.dm
  html/changelogs/lamasmaster-PR-33.yml
  maps/torch/torch.dm
  maps/~mapsystem/maps.dm
  modular_boh/code/items/clothing/solgov-accessory.dm
  modular_boh/code/modules/culture_descriptor/culture/cultures_human.dm
  modular_boh/code/modules/culture_descriptor/faction/factions_human.dm
  modular_boh/code/modules/culture_descriptor/location/locations_human.dm
  modular_boh/code/modules/mob/language/human/gaian.dm
  modular_boh/code/modules/species/shell/shell.dm
  modular_mithra/code/modules/species/station/custom.dm
Labels: Lamasmaster go brrrr, Review Required 👓, Tweak

#37 Makes Roboticist a research role again. Removes Biomech. Gives Roboticist basic medical access.
  html/changelogs/Vhbraz-37.yml
  maps/torch/job/command_jobs.dm
  maps/torch/job/engineering_jobs.dm
  maps/torch/job/torch_jobs.dm
  modular_boh/code/items/cards_ids.dm
  modular_boh/code/modules/jobs/jobs.dm
  modular_boh/code/modules/jobs/outfits/vesta_outfits.dm
Labels: Changes Requested, Removal

#41 Merchant changes.
  baystation12.dme
  code/datums/trading/weaponry.dm
  code/modules/item_worth/worths_list.dm
  html/changelogs/vhbraz-41.yml
  modular_boh/code/datums/trading/weaponry.dm
Labels: Rework

#44 Ballistic sideram begone
  html/changelogs/lamasmaster-PR-44.yml
  modular_boh/code/modules/boxes.dm
Labels: Changes Requested, Lamasmaster go brrrr, Tweak

#31 Removes most SCG logos and puts NTEF logos on the shuttles
  html/changelogs/lamasmaster-PR-31.yml
  maps/torch/torch1_deck5.dmm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
Labels: Changes Requested, Lamasmaster go brrrr, Map

#42 Slight loadout fixes
  html/changelogs/lamasmaster-PR-42.yml
  modular_boh/code/game/loadout/loadout_accessories.dm
  modular_boh/loadouts/custom_loadouts.dm
Labels: Changes Requested, Fix

#47 AI default lawset changes
  code/datums/ai_law_sets.dm
  html/changelogs/lamasmaster-PR-47.yml
Labels: Review Required 👓, Tweak

#50 Faction reshuffle
  baystation12.dme
  code/__defines/culture.dm
  code/modules/culture_descriptor/culture/cultures_ipc.dm
  code/modules/species/station/machine.dm
  html/changelogs/lamasmaster-PR-50.yml
  maps/torch/torch.dm
  maps/~mapsystem/maps.dm
  modular_boh/code/modules/culture_descriptor/culture/cultures_ipc.dm
  modular_boh/code/modules/culture_descriptor/faction/factions_human.dm
  modular_boh/code/modules/species/shell/shell.dm
Labels: Lamasmaster go brrrr, Review Required 👓, Tweak

#51 Adds NSFW tab back to flavor text
  code/modules/client/preference_setup/general/04_flavor.dm
  html/changelogs/lamasmaster-PR-51.yml
Labels: Feature, Review Required 👓

#56 Description Changes
  code/hub.dm
  html/changelogs/alanii-PR-56.yml
  maps/torch/job/command_jobs.dm
  maps/torch/job/corporate_jobs.dm
  maps/torch/job/engineering_jobs.dm
  maps/torch/job/exploration_jobs.dm
  maps/torch/job/misc_jobs.dm
  maps/torch/job/service_jobs.dm
  maps/torch/job/supply_jobs.dm
  maps/torch/torch_define.dm
  modular_boh/code/game/ranks/vesta_ranks.dm
  modular_boh/code/modules/jobs/jobs.dm
Labels: Fix, Tweak

#48 Reverts total darkness while KO
  code/modules/mob/living/life.dm
  html/changelogs/purplepineapple-PR-48.yml
Labels: Feature, Review Required 👓

#49 Reverts space lube removal
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mob/living/silicon/robot/modules/module_janitor.dm
  code/modules/organs/internal/species/vox.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/xenoarcheaology/finds/special.dm
  html/changelogs/purplepineapple-PR-49.yml
Labels: Feature, Review Required 👓

#52 Ascent hestia equipment
  html/changelogs/lamasmaster-PR-52.yml
  maps/away/ascent/ascent-1.dmm
  maps/away/ascent/ascent.dm
  maps/away/ascent/ascent_jobs.dm
  modular_boh/code/modules/ascent/ascent_general.dm
  modular_boh/code/modules/ascent/ascent_implants.dm
Labels: Feature

#60 Makes Navy the default marine uniform | Reverts Lamamaster's terrible PR
  baystation12.dme
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  html/changelogs/lamasmaster-PR-45.yml
  modular_boh/code/items/clothing/solgov-under.dm
  modular_boh/code/modules/client/preference_setup/general/05_ooc_notes.dm
  modular_boh/code/modules/datums/uniforms_marine_corps.dm
  modular_boh/code/modules/jobs/outfits/vesta_outfits.dm
  modular_boh/loadouts/custom_loadouts.dm
Labels: Fix, Removal, Tweak

#53 Skill points are no longer age dependent.
  code/modules/species/species.dm
Labels: Review Required 👓, Tweak

#64 Coup de Grace on tan/urban
  code/_global_vars/configuration.dm
  code/modules/client/preference_setup/loadout/lists/storage.dm
  html/changelogs/purplepineapple-PR-64.yml
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_storage.dm
  maps/torch/loadout/loadout_suit.dm
  maps/torch/torch.dm
  modular_boh/code/game/loadout/loadout_accessories.dm
  modular_boh/loadouts/custom_loadouts.dm
Labels: Fix, Review Required 👓, Rework

#58 Makes the mess hall prettier
  html/changelogs/vhbraz-PR-58.yml
  maps/torch/torch3_deck3.dmm
Labels: Map, Review Required 👓

#63 Revert "Inflatables, unpowered doors and firedoors can no longer be closed on people." and related stuff.
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/simple.dm
  code/game/objects/structures/inflatable.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  maps/away/meatstation/meatstation.dmm
Labels: Runtime, Tweak

#88 Adds Nurse alt-title to Medical Resident
  maps/torch/job/medical_jobs.dm
Labels: Changes Requested, Feature

#94 Locker readjustment
  code/modules/fabrication/designs/general/designs_arms_ammo.dm
  html/changelogs/lamasmaster-PR-94.yml
  maps/torch/structures/closets/security.dm
  modular_boh/code/modules/boxes.dm
  modular_boh/code/modules/firearms.dm
  modular_boh/code/modules/projectiles/ammunition/bullets.dm
  modular_boh/code/modules/projectiles/projectiles/bullets.dm
Labels: Changes Requested, Fix

#95 Point and resist adventure
  code/_onclick/click.dm
  interface/interface.dm
  interface/skin.dmf
Labels: Feature

#126 Missing defines for cloaks
  baystation12.dme
  html/changelogs/lamasmaster-PR-126.yml
  modular_boh/code/items/clothing/boh_clothing.dm
  modular_boh/code/modules/clothing.dm
  modular_boh/icon/boh/obj/clothing/obj_cloak.dmi
  modular_boh/icon/obj/obj_cloak_boh.dmi
  modular_boh/loadouts/custom_loadouts.dm
Labels: Review Required 👓, Tweak

#78 Pork Adjustments
  html/changelogs/lamasmaster-PR-78.yml
  maps/torch/torch.dm
  maps/torch/torch1_deck5.dmm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
  maps/torch/torch_areas.dm
  maps/torch/torch_overmap.dm
  maps/torch/torch_presets.dm
  maps/torch/torch_shuttles.dm
  modular_boh/code/game/machinery/vending.dm
  modular_boh/code/game/structures/closets/closets.dm
  modular_boh/maps/boh_areas.dm
Labels: Feature, Lamasmaster go brrrr

#127 Green into Urban
  html/changelogs/lamasmaster-PR-127.yml
  modular_boh/code/modules/datums/uniforms_marine_corps.dm
  modular_boh/loadouts/custom_loadouts.dm
Labels: Changes Requested, Tweak

#124 Restores power production of ascent fusion stack to (un)reasonable levels
  code/modules/ascent/ascent_machines.dm
  html/changelogs/memedhams-PR-124.yml
Labels: Missing Changelog, Tweak

#130 Slight Map Adjustments
  html/changelogs/lamasmaster-PR-130.yml
  maps/torch/torch2_deck4.dmm
  maps/torch/torch5_deck1.dmm
Labels: Fix, Map, Tweak

#132 Psyker Mini-Changes
  code/modules/psionics/faculties/psychokinesis.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelogs/superhats-PR-132.yml
  modular_boh/code/modules/chemicals.dm
Labels: Fix, Tweak

#131 Materials for researchers.
  html/changelogs/WidelecMaker-PR-131.yml
  maps/torch/loadout/loadout_eyes.dm
Labels: Tweak

#135 Minor command support fixes.
  html/changelogs/torque4607-PR-135.yml
  maps/torch/torch6_bridge.dmm
  modular_boh/code/modules/jobs/jobs.dm
Labels: Tweak

#125 Re-adds tritonian gills
  code/modules/species/station/human_subspecies.dm
  html/changelogs/N8Toe-PR-125.yml
Labels: Feature

#142 Removes GAS, Adherent, Diona from antag.
  code/game/antagonist/antagonist.dm
  code/game/antagonist/antagonist_helpers.dm
  html/changelogs/torque4607-PR-142.yml
Labels: Tweak

#137 Bearcat Rework
  html/changelogs/purplepineapple-PR-137.yml
  maps/away/bearcat/bearcat-1.dmm
  maps/away/bearcat/bearcat-2.dmm
  maps/away/bearcat/bearcat.dm
  maps/away/bearcat/bearcat_areas.dm
  maps/away/bearcat/bearcat_shuttles.dm
Labels: Feature, Map, Rework

#149 new exoplanet ruins
  html/changelogs/gilvian-PR-149.yml
  maps/random_ruins/exoplanet_ruins/abanxenoarch/abanxenoarch.dm
  maps/random_ruins/exoplanet_ruins/abanxenoarch/abanxenoarch.dmm
  maps/random_ruins/exoplanet_ruins/crashsupshut/crashsupshut.dm
  maps/random_ruins/exoplanet_ruins/crashsupshut/crashsupshut.dmm
Labels: Map

#153 KILL BAY(Or how I reverted the most griping change)
  code/modules/fabrication/designs/general/designs_devices_components.dm
  html/changelogs/yawet330-4.yml
Labels: Changes Requested, Tweak

#157 Adherent whitelist fixes
  code/modules/species/station/adherent.dm
  html/changelogs/superhats-PR-157.yml
Labels: Tweak

#155 Expands Verne Species
  html/changelogs/BladeburstNINJA-PR-155.yml
  maps/away/verne/verne_jobs.dm
Labels: Missing Changelog, Tweak

#160 Changes the alert level screens back to normal
  html/changelogs/purplepineapple-PR-160.yml
  icons/misc/security_state.dmi
  maps/torch/icons/security_state.dmi
Labels: Sprites

#156 merchant tweeks
  html/changelogs/gilvian-PR-156.yml
  maps/torch/torch_z1_admin.dmm
Labels: Map

#171 Balance changes to skills/EPP + UI fixes + snapping emote
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/emotes/definitions/audible.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
  code/modules/species/species.dm
  html/changelogs/purplepineapple-PR-171.yml
  maps/torch/items/solbanner.dm
  maps/torch/items/summarydocuments.dm
  maps/torch/job/command_jobs.dm
  maps/torch/job/research_jobs.dm
  maps/torch/job/security_jobs.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/torch_overmap.dm
  modular_boh/code/modules/clothing/spacesuit/void.dm
  modular_boh/code/modules/firearms.dm
  modular_boh/loadouts/custom_loadouts.dm
  sound/misc/fsnap1.ogg
  sound/misc/fsnap2.ogg
  sound/misc/fsnap3.ogg
Labels: Feature, Fix, Review Required 👓, Tweak

#123 Rank Overhaul
  html/changelogs/hekzder-PR-123.yml
  maps/torch/icons/assignment_hud.dmi
  maps/torch/job/engineering_jobs.dm
  maps/torch/job/exploration_jobs.dm
  maps/torch/job/medical_jobs.dm
  maps/torch/job/research_jobs.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/torch6_bridge.dmm
  modular_boh/code/modules/jobs/jobs.dm
  modular_boh/code/modules/jobs/outfits/vesta_outfits.dm
  modular_boh/code/modules/jobs/torch_jobs_vesta.dm
Labels: Removal, Review Required 👓, Tweak

#174 Adds exactly one new hat.
  html/changelogs/thatguyfromlife-PR-174.yml
  maps/torch/job/medical_jobs.dm
  maps/torch/loadout/loadout_head.dm
Labels: Changes Requested, Feature

#151 Adjusts 454 to be more reasonable
  html/changelogs/yawet330-2.yml
  modular_boh/code/modules/projectiles/projectiles/bullets.dm
Labels: Changes Requested, Tweak

#150 Adds CO Ammo back to the autolathe
  html/changelogs/yawet330-3.yml
  modular_boh/code/modules/designs/designs_arms_ammo.dm
Labels: Changes Requested, Tweak

#181 Adds O-2 Bridge Officer back
  html/changelogs/purplepineapple-PR-181.yml
  modular_boh/code/modules/jobs/torch_jobs_vesta.dm
Labels: Fix

#178 Fixes Legalese
  code/modules/mob/language/human/misc/gutter.dm
  code/modules/mob/language/human/selenian.dm
  code/modules/mob/living/silicon/robot/modules/_module.dm
  code/modules/mob/skills/skill.dm
  html/changelogs/purplepineapple-PR-178.yml
Labels: Feature

#179 Makes the 454 not a holdout pistol(TM)
  html/changelogs/yawet330-5.yml
  modular_boh/code/modules/projectiles/ammunition/bullets.dm
  modular_boh/code/modules/projectiles/projectiles/bullets.dm
Labels: Tweak

#180 Boot changes
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/clothing/shoes/miscellaneous.dm
  html/changelogs/lamasmaster-PR-180.yml
  icons/mob/onmob/onmob_feet.dmi
  icons/obj/clothing/obj_feet.dmi
  maps/torch/loadout/loadout_shoes.dm
  maps/torch/torch.dm
  modular_boh/code/items/clothing/boh_clothing.dm
  modular_boh/loadouts/custom_loadouts.dm
Labels: Changes Requested, Sprites, Tweak

#184 Spritepack #3 Devices & Misc
  html/changelogs/pebblesthe2nd-PR-184.yml
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/obj/assemblies.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/device.dmi
  icons/obj/guns/flaregun.dmi
  icons/obj/items.dmi
  icons/obj/photography.dmi
  icons/obj/storage.dmi
  icons/obj/weapons/melee_physical.dmi
  icons/obj/xenoarchaeology.dmi
Labels: Sprites
