Repository VestaOfOrion/Vesta.Bay, pull requests merged in 2021-02, with the labels that each got.

#315 New Parts for machines
  baystation12.dme
  html/changelogs/rogueshadowwalker-PR- 315.yml
  modular_boh/code/modules/organs/robolimbs.dm
  modular_boh/icon/mob/human_races/cyberlimbs/c-tech/c_beast.dmi
  modular_boh/icon/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt1.dmi
  modular_boh/icon/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt2.dmi
  modular_boh/icon/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt3.dmi
  modular_boh/icon/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_main.dmi
Labels: Feature

#339 Navy SMC service
  html/changelogs/Firefox13-PR-338.yml
  modular_boh/icon/mob/onmob_head_solgov.dmi
  modular_boh/icon/mob/onmob_suit_solgov.dmi
  modular_boh/icon/mob/onmob_under_solgov.dmi
  modular_boh/icon/obj/obj_head_solgov.dmi
  modular_boh/icon/obj/obj_suit_solgov.dmi
  modular_boh/icon/obj/obj_under_solgov.dmi
Labels: Rework, Sprites

#342 Removes underage-ing from fountain of youth
  code/game/objects/structures/fountain.dm
  html/changelogs/evenindeathistillserve-PR-342.yml
Labels: Tweak

#345 Lets you pull face-masks down
  code/modules/clothing/masks/gasmask.dm
  html/changelogs/evenindeathistillserve-PR-345.yml
  icons/obj/clothing/obj_mask.dmi
Labels: Tweak

#344 Removes delay on drawing boot-items
  html/changelogs/evenindeathistillserve-PR-344.yml
  modular_boh/code/modules/clothing/clothing.dm
Labels: Tweak

#348 Unwrenching atmos devices ignores pressure
  code/modules/atmospherics/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/components/binary_devices/pump.dm
  code/modules/atmospherics/components/omni_devices/omni_base.dm
  code/modules/atmospherics/components/portables_connector.dm
  code/modules/atmospherics/components/tvalve.dm
  code/modules/atmospherics/components/unary/heat_exchanger.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/atmospherics/components/unary/vent_scrubber.dm
  code/modules/atmospherics/components/valve.dm
  html/changelogs/evenindeathistillserve-PR-348.yml
Labels: Tweak
