Repository VestaOfOrion/Vesta.Bay, pull requests merged in 2021-03, with the labels that each got.

#346 Restores pre-rebayse autolathe lists
  code/__defines/guns.dm
  code/modules/fabrication/designs/general/designs_arms_ammo.dm
  code/modules/fabrication/designs/general/designs_devices_components.dm
  code/modules/fabrication/designs/general/designs_general.dm
  code/modules/fabrication/designs/general/designs_tools.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullets.dm
  html/changelogs/evenindeathistillserve-PR-346.yml
  sound/weapons/gunshot/new_shotgun.ogg
Labels: Tweak

#343 RIG gauntlets cover gloves
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  html/changelogs/evenindeathistillserve-PR-343.yml
  modular_boh/code/items/clothing/solgov-hands.dm
Labels: Tweak

#363 Turret Addition v2
  html/changelogs/Zulu0009-PR-363.yml
  maps/away/bearcat/bearcat-1.dmm
  maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
  maps/torch/z1_admin.dmm
Labels: Map

#364 Sound Changes
  maps/torch/torch_security_state.dm
  sound/AI/torch/abandonship.ogg
  sound/AI/torch/aliens.ogg
  sound/AI/torch/commandreport.ogg
  sound/AI/torch/electricalstormmajor.ogg
  sound/AI/torch/electricalstormmoderate.ogg
  sound/AI/torch/gravanomalies.ogg
  sound/AI/torch/meteors.ogg
  sound/AI/torch/outbreak5.ogg
  sound/AI/torch/outbreak7.ogg
  sound/AI/torch/outbreak7viral.ogg
  sound/AI/torch/poweroff.ogg
  sound/AI/torch/poweron.ogg
  sound/AI/torch/radiation.ogg
  sound/AI/torch/radiation2.ogg
  sound/AI/torch/spanomalies.ogg
  sound/misc/notice1.ogg
  sound/misc/orangealert1.ogg
  sound/misc/redalert1.ogg
  sound/misc/violetalert.ogg
  test/check-paths.sh
Labels: Sounds
