Repository VestaOfOrion/Vesta.Bay, pull requests merged in 2021-01, with the labels that each got.

#183 adds binos and GPS to colony + ascent seedship also getting them
  html/changelogs/gilvian-PR-183.yml
  maps/away/ascent/ascent-1.dmm
  maps/random_ruins/exoplanet_ruins/playablecolony/colony.dmm
Labels: Feature

#177 Engineering Ports
  baystation12.dme
  code/datums/supplypacks/dispcarts.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/paint_sprayer.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/tools/handdrill.dm
  code/modules/atmospherics/pipes.dm
  code/modules/fabrication/designs/general/designs_general.dm
  code/modules/power/fusion/core/core_field.dm
  code/modules/power/fusion/fuel_assembly/fuel_injector.dm
  code/modules/power/fusion/fusion_reactions.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/dispenser/cartridge_presets.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  html/changelogs/evenindeathistillserve-PR-177.yml
  maps/away/casino/casino.dmm
  maps/torch/structures/closets/engineering.dm
  sound/items/change_drill.ogg
  test/check-paths.sh
Labels: Do not Merge ❌, Feature, Second Review Required 👓

#191 Vox Merchant: Himbo Edition
  code/modules/clothing/spacesuits/rig/suits/vox.dm
  code/modules/species/outsider/vox.dm
  html/changelogs/superhats-PR-191.yml
  maps/torch/job/torch_jobs.dm
Labels: Feature

#202 Grenades are now deadly.
  code/game/objects/items/weapons/grenades/explosive.dm
  html/changelogs/vhbraz-PR-202.yml
Labels: Balance Change

#205 Reverts "Implements single transferable vote" from Baystation.
  code/datums/vote/add_antag.dm
  code/datums/vote/custom.dm
  code/datums/vote/gamemode.dm
  code/datums/vote/restart.dm
  code/datums/vote/transfer.dm
  code/datums/vote/vote.dm
  html/changelogs/hekzder-PR-205.yml
Labels: Tweak

#216 More jerraman
  html/changelogs/superhats-PR-216.yml
  modular_boh/code/modules/boxes.dm
Labels: Tweak

#209 Bluesec
  code/__defines/colors.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/clothing/glasses/eyepatch.dm
  code/modules/clothing/under/accessories/armband.dm
  html/changelogs/lamasmaster-PR-209.yml
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/mob/onmob/onmob_accessories.dmi
  icons/mob/onmob/onmob_back.dmi
  icons/mob/onmob/onmob_ears.dmi
  icons/mob/onmob/onmob_eyes.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/mob/onmob/onmob_suit.dmi
  icons/obj/clothing/obj_accessories.dmi
  icons/obj/clothing/obj_eyes.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/grenade.dmi
  icons/obj/radio.dmi
  icons/obj/storage.dmi
  maps/torch/icons/assignment_hud.dmi
  maps/torch/icons/mob/onmob_accessories_solgov.dmi
  maps/torch/icons/mob/onmob_head_solgov.dmi
  maps/torch/icons/obj/obj_accessories_solgov.dmi
  maps/torch/icons/obj/obj_head_solgov.dmi
  maps/torch/items/cards_ids.dm
  maps/torch/items/clothing/solgov-accessory.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/structures/closets/security.dm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
  modular_boh/code/game/loadout/loadout_accessories.dm
  modular_boh/code/items/clothing/solgov-accessory.dm
  modular_boh/icon/boh/items/z9b.dmi
  modular_boh/icon/mob/onmob_accessories_solgov.dmi
  modular_boh/icon/mob/onmob_head_solgov.dmi
  modular_boh/icon/mob/onmob_under_solgov.dmi
  modular_boh/icon/obj/obj_accessories_solgov.dmi
  modular_boh/icon/obj/obj_head_solgov.dmi
  modular_boh/loadouts/custom_loadouts.dm
Labels: Sprites

#217 Adjusts various skill points
  html/changelogs/hekzder-PR-217.yml
  maps/torch/job/command_jobs.dm
  maps/torch/job/medical_jobs.dm
  maps/torch/job/research_jobs.dm
  modular_boh/code/modules/jobs/jobs.dm
Labels: Balance Change, Review Required 👓

#229 Fixes issues with Prospectors.
  html/changelogs/vhbraz-PR-229.yml
  modular_boh/code/modules/jobs/outfits/vesta_outfits.dm
Labels: Fix

#219 Spring cleanup no 1
  code/game/objects/structures/iv_drip.dm
  html/changelogs/pebblesthe2nd-PR-219.yml
  icons/obj/ascent.dmi
  icons/obj/chemical.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/device.dmi
  icons/obj/iv_drip.dmi
  icons/obj/tools.dmi
Labels: Sprites

#230 Kills the meme
  html/changelogs/vhbraz-PR-230.yml
  maps/torch/z1_admin.dmm
Labels: Fix, Map

#228 Marine uniform fluff
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/gloves.dm
  html/changelogs/lamasmaster-PR-228.yml
  icons/mob/onmob/onmob_feet.dmi
  icons/mob/onmob/onmob_hands.dmi
  icons/obj/clothing/obj_feet.dmi
  icons/obj/clothing/obj_hands.dmi
  modular_boh/code/items/clothing/boh_clothing.dm
  modular_boh/icon/mob/species/unathi/onmob_under_solgov_unathi.dmi
Labels: Lamasmaster go brrrr, Sprites

#232 Adds Federal Protection Agent
  html/changelogs/purplepineapple-PR-232.yml
  maps/torch/icons/assignment_hud.dmi
  maps/torch/job/command_jobs.dm
  maps/torch/job/corporate_jobs.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/structures/closets/misc.dm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
  modular_boh/code/game/structures/closets/closets.dm
  modular_boh/code/items/cards_ids.dm
  modular_boh/code/modules/datums/access.dm
  modular_boh/code/modules/jobs/jobs.dm
  modular_boh/code/modules/jobs/outfits/vesta_outfits.dm
Labels: Feature, Review Required 👓

#233 Cloaks (and a typo) fix
  html/changelogs/lamasmaster-PR-233.yml
  modular_boh/code/items/clothing/boh_accessory.dm
  modular_boh/code/items/clothing/boh_clothing.dm
  modular_boh/icon/boh/mob/onmob/onmob_cloak.dmi
  modular_boh/icon/boh/obj/clothing/obj_cloak.dmi
  modular_boh/icon/mob/onmob_cloak.dmi
  modular_boh/icon/mob/onmob_cloak_boh.dmi
  modular_boh/icon/obj/obj_cloak.dmi
Labels: Fix, Lamasmaster go brrrr

#226 Adds manual shuttle landing
  baystation12.dme
  code/controllers/subsystems/shuttle.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/life.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/observer/eye/eye.dm
  code/modules/mob/observer/eye/freelook/ai/cameranet.dm
  code/modules/mob/observer/eye/freelook/ai/chunk.dm
  code/modules/mob/observer/eye/freelook/ai/eye.dm
  code/modules/mob/observer/eye/freelook/ai/update_triggers.dm
  code/modules/mob/observer/eye/freelook/chunk.dm
  code/modules/mob/observer/eye/freelook/cult/cultnet.dm
  code/modules/mob/observer/eye/freelook/cult/mask.dm
  code/modules/mob/observer/eye/freelook/following.dm
  code/modules/mob/observer/eye/freelook/freelook.dm
  code/modules/mob/observer/eye/freelook/life.dm
  code/modules/mob/observer/eye/freelook/logging.dm
  code/modules/mob/observer/eye/freelook/read_me.dm
  code/modules/mob/observer/eye/freelook/update_triggers.dm
  code/modules/mob/observer/eye/freelook/visualnet.dm
  code/modules/mob/observer/eye/landing_eye/landing_eye.dm
  code/modules/mob/observer/virtual/helpers.dm
  code/modules/mob/skills/skill.dm
  code/modules/overmap/exoplanets/exoplanet.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/shuttle.dm
  code/modules/shuttles/landmarks.dm
  code/modules/shuttles/shuttle.dm
  code/modules/spells/racial_wizard.dm
  icons/obj/action_buttons/actions.dmi
  nano/templates/shuttle_control_console_exploration.tmpl
Labels: Feature

#239 Fixes the QX-2
  html/changelogs/vhbraz-PR-239.yml
  modular_boh/code/modules/projectiles/ammunition/bullets.dm
  modular_boh/code/modules/projectiles/guns/projectile/automatic.dm
  modular_boh/icon/obj/guns/skrell_shotgun.dmi
Labels: Balance Change, Fix

#243 Mapping/Holster fixes for the SSV
  html/changelogs/vhbraz-PR-243.yml
  maps/away/skrellscoutship/skrellscoutship.dm
  maps/away/skrellscoutship/skrellscoutship_revamp.dmm
Labels: Fix, Map

#236 More random loot + a bit more starting cash for merchants
  html/changelogs/Spum-PR-merchantshit.yml
  maps/torch/z1_admin.dmm
Labels: Map, Review Required 👓, Tweak

#241 Tablet: sprite on hand.
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  html/changelogs/Alejodbort2-PR-241.yml
  icons/mob/onmob/items/lefthand.dmi
  icons/mob/onmob/items/righthand.dmi
Labels: Sprites

#248 Officer messhall, cargo, and merchant dock changes
  html/changelogs/lamasmaster-PR-248.yml
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
Labels: Map, Review Required 👓

#246 Off-ship Love
  html/changelogs/hekzder-PR-246.yml
  maps/away/bearcat/bearcat-1.dmm
  maps/away/bearcat/bearcat-2.dmm
  maps/away/bearcat/bearcat_jobs.dm
  maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dm
  maps/random_ruins/exoplanet_ruins/playablecolony/colony.dmm
  maps/random_ruins/exoplanet_ruins/playablecolony/playablecolony.dm
  maps/random_ruins/exoplanet_ruins/playablecolony2/playablecolony2.dm
Labels: Balance Change, Map

#252 Fixes Lab Technician access
  modular_boh/code/modules/jobs/outfits/vesta_outfits.dm
  modular_boh/code/modules/jobs/torch_jobs_vesta.dm
Labels: Fix

#264 Mess Hall Changes / Map Bugfixes
  icons/obj/vending.dmi
  maps/torch/torch3_deck3.dmm
  maps/torch/torch6_bridge.dmm
  modular_boh/maps/boh_areas.dm
Labels: Map, Sprites

#262 Baymerge go brrrrrrr
  code/controllers/subsystems/garbage.dm
  code/modules/admin/buildmode/areas.dm
  code/modules/overmap/ships/ship.dm
  html/changelogs/vhbraz-PR-262.yml
  test/check-paths.sh
Labels: Admin, Changes Requested, Tweak

#274 Ascent language tweaks V2
  code/modules/mob/living/silicon/robot/preset.dm
Labels: Fix

#271 Stop All Sounds button
  code/game/sound.dm
  html/changelogs/Firefox13-PR-271.yml
Labels: Feature

#273 Red Mining Drills, some sprite issues fixed
  html/changelogs/pebblesthe2nd-PR-273.yml
  icons/mob/onmob/items/lefthand.dmi
  icons/mob/onmob/items/righthand.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/chemical.dmi
  icons/obj/device.dmi
  icons/obj/photography.dmi
  icons/obj/tools.dmi
Labels: Sprites

#265 AI turret rearrangment and Aux storage remap
  html/changelogs/lamasmaster-PR-265.yml
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
Labels: Map

#266 Alien Organs Update
  code/modules/organs/internal/species/insectoid.dm
  code/modules/organs/internal/species/nabber.dm
  code/modules/organs/internal/species/skrell.dm
  code/modules/organs/internal/species/unathi.dm
  code/modules/organs/internal/species/vox.dm
  code/modules/species/outsider/vox.dm
  code/modules/species/station/nabber.dm
  code/modules/species/station/station.dm
  html/changelogs/pebblesthe2nd-PR-266.yml
  icons/mob/human_races/species/nabber/body.dmi
  icons/mob/human_races/species/nabber/organs_nabber.dmi
  icons/mob/human_races/species/skrell/organs.dmi
  icons/mob/human_races/species/unathi/organs.dmi
  icons/mob/human_races/species/vox/organs_vox.dmi
Labels: Sprites

#289 Uniform Overhaul
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  html/changelogs/purplepineapple-PR-289.yml
  maps/torch/loadout/loadout_suit.dm
  maps/torch/torch.dm
  modular_boh/code/game/loadout/loadout_accessories.dm
  modular_boh/code/modules/datums/uniform_vendor_boh.dm
  modular_boh/code/modules/datums/uniforms_marine_corps.dm
  modular_boh/loadouts/custom_loadouts.dm
Labels: Feature, Tweak

#292 Fixes chocolate milk
  code/game/machinery/biogenerator.dm
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  html/changelogs/evenindeathistillserve-PR-69.yml
  maps/away/casino/casino.dmm
Labels: Fix

#294 Fixes glass windows
  code/__defines/colors.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/window.dm
  code/modules/turbolift/turbolift_door.dm
  html/changelogs/vhbraz-PR-294.yml
Labels: Fix

#269 Expand access to SGR, SFP, CL, APA, and SEA
  html/changelogs/Electric-PR-269.yml
  modular_boh/code/modules/jobs/jobs.dm
Labels: Tweak

#296 Some minor SSV tweaks.
  html/changelogs/vhbraz-PR-296.yml
  maps/away/skrellscoutship/skrellscoutship.dm
  maps/away/skrellscoutship/skrellscoutship_revamp.dmm
Labels: Map, Tweak

#305 Merges recent bay PRs
  baystation12.dme
  code/game/machinery/OpTable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/simple.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/newscaster.dm
  code/modules/admin/admin.dm
  code/modules/admin/buildmode/_datums/mobspawner.dm
  code/modules/admin/buildmode/mob_spawning.dm
  code/modules/admin/create_object.dm
  code/modules/admin/topic.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/random_map/drop/supply.dm
  code/modules/tables/interactions.dm
  code/modules/xenoarcheaology/triggers/force.dm
  icons/mob/human_races/cyberlimbs/bishop/bishop_main.dmi
  icons/mob/human_races/cyberlimbs/bishop/bishop_rook.dmi
  icons/mob/human_races/cyberlimbs/hephaestus/hephaestus_main.dmi
  icons/mob/human_races/cyberlimbs/hephaestus/hephaestus_titan.dmi
  icons/mob/human_races/cyberlimbs/morpheus/morpheus_main.dmi
  icons/mob/human_races/cyberlimbs/nanotrasen/nanotrasen_main.dmi
  icons/mob/human_races/cyberlimbs/xion/xion_main.dmi
  icons/mob/human_races/cyberlimbs/zenghu/zenghu_main.dmi
  icons/mob/human_races/cyberlimbs/zenghu/zenghu_spirit.dmi
  maps/antag_spawn/mercenary/mercenary.dm
  maps/antag_spawn/mercenary/mercenary_base.dmm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch_overmap.dm
Labels: Bay Update, Review Required 👓

#297 Robotics touch-up
  html/changelogs/Firefox13-PR-297.yml
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
Labels: Map

#301 Sprite Misc Update no. 2
  html/changelogs/pebblesthe2nd-PR-301.yml
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/mob/onmob/onmob_back.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/chemical.dmi
  icons/obj/defibrillator.dmi
  icons/obj/device.dmi
  icons/obj/guns/flaregun.dmi
  icons/obj/hydroponics_machines.dmi
  icons/obj/mining.dmi
  icons/obj/photography.dmi
  icons/obj/power.dmi
  icons/obj/storage.dmi
  icons/obj/suitcooler.dmi
  icons/obj/tools.dmi
  icons/turf/flooring/decals.dmi
  maps/torch/icons/obj/explshotgun.dmi
Labels: Sprites

#303 New Abstract Exoplanet ruin.
  html/changelogs/gilvian-PR-303.yml
  maps/random_ruins/exoplanet_ruins/abstractartifact/abanxenoarch.dm
  maps/random_ruins/exoplanet_ruins/abstractartifact/abstractartifact.dmm
Labels: Map

#304 Re-adds some zombie tweaks lost in the rebase
  code/game/machinery/Sleeper.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/species/outsider/zombie.dm
  maps/random_ruins/exoplanet_ruins/datacapsule/datacapsule.dm
  modular_boh/code/modules/chemicals.dm
Labels: Tweak

#298 Adds item pushing/sliding on table surfaces
  code/_onclick/drag_drop.dm
  code/modules/tables/interactions.dm
  html/changelogs/wb13-PR-298.yml
Labels: Feature

#281 Glasses for the masses
  baystation12.dme
  code/game/objects/effects/landmarks.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/prescription.dm
  code/modules/clothing/glasses/prescsun.dm
  code/modules/clothing/glasses/sunglasses.dm
  code/modules/item_worth/worths_list.dm
  html/changelogs/pebblesthe2nd-PR-281.yml
  icons/mob/onmob/onmob_eyes.dmi
  icons/obj/clothing/obj_eyes.dmi
Labels: Review Required 👓, Sprites

#306 removes the nurse alt-title from medical resident, gives it to physician
  html/changelogs/anconfuzedrock-PR-306.yml
  maps/torch/job/medical_jobs.dm
Labels: Balance Change, Missing Changelog, Review Required 👓, Tweak

#311 Infantry Symbols added to their lockers
  html/changelogs/Alanii-PR-311.yml
  icons/obj/closets/decals/closet.dmi
  modular_boh/code/game/structures/closets/closets.dm
Labels: Tweak

#302 Fixes raider dock
  html/changelogs/lamasmaster-PR-302.yml
  maps/torch/torch2_deck4.dmm
Labels: Fix, Lamasmaster go brrrr, Map

#314 Allow tablets to be put in the belt slot
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
Labels: Tweak

#313 Allow wallets to fit playing cards
  code/game/objects/items/weapons/storage/wallets.dm
Labels: Tweak

#316 Suit Icons update
  html/changelogs/pebblesthe2nd-PR-316.yml
  icons/mob/onmob/onmob_suit.dmi
  icons/obj/clothing/obj_eyes.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/weapons/melee_physical.dmi
  maps/torch/icons/obj/obj_suit_solgov.dmi
  modular_boh/icon/boh/obj/clothing/longlabcoats.dmi
  modular_boh/icon/obj/obj_suit_solgov.dmi
Labels: Sprites

#309 Bearcat Tweaks
  baystation12.dme
  html/changelogs/purplepineapple-PR-309.yml
  maps/away/bearcat/bearcat-1.dmm
  maps/away/bearcat/bearcat-2.dmm
  maps/away/bearcat/bearcat_areas.dm
  modular_boh/code/modules/cycler.dm
Labels: Map, Tweak

#318 Merges recent BAY PRs
  code/__defines/_planes+layers.dm
  code/_onclick/item_attack.dm
  code/datums/mil_ranks.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/admin/view_variables/vv_set_handlers.dm
  code/modules/atmospherics/components/binary_devices/binary_atmos_base.dm
  code/modules/atmospherics/components/omni_devices/omni_base.dm
  code/modules/atmospherics/components/valve.dm
  code/modules/detectivework/tools/rag.dm
  code/modules/events/rogue_drones.dm
  code/modules/mob/language/human/euro.dm
  code/modules/submaps/submap_join.dm
  code/unit_tests/map_tests.dm
  maps/away/bearcat/bearcat-2.dmm
  maps/away/casino/casino.dmm
  maps/away/lost_supply_base/lost_supply_base.dmm
  maps/away/miningstation/miningstation.dmm
  maps/away/slavers/slavers_base.dmm
  maps/random_ruins/exoplanet_ruins/oldpod/oldpod.dmm
  maps/random_ruins/exoplanet_ruins/radshrine/radshrine.dmm
  maps/torch/torch6_bridge.dmm
Labels: Bay Update, Review Required 👓

#317 Adds access restrictions for the engi polytool.
  html/changelogs/vhbraz-PR-317.yml
  modular_boh/loadouts/custom_loadouts.dm
Labels: Balance Change, Review Required 👓

#325 Revert "Adds access restrictions for the engi polytool."
  html/changelogs/vhbraz-PR-317.yml
  html/changelogs/yawet330-PR-325.yml
  modular_boh/loadouts/custom_loadouts.dm
Labels: Revert

#327 Add aluminum sheets and a powerloader mech to the merchant station
  html/changelogs/Electric-PR-327.yml
  maps/torch/z1_admin.dmm
Labels: Map

#321 Adds Skrellian gill covers + adds them to Xenowear loadout
  baystation12.dme
  html/changelogs/listerla-PR-321.yml
  modular_boh/code/items/clothing/boh_masks.dm
  modular_boh/icon/boh/mob/onmob/onmob_mask.dmi
  modular_boh/icon/boh/obj/clothing/obj_mask.dmi
  modular_boh/loadouts/custom_loadouts.dm
Labels: Sprites

#328 Allows genemodders to become most off-ship roles.
  code/__defines/mobs.dm
  html/changelogs/embershinori-PR-328.yml
  maps/away/ascent/ascent_jobs.dm
Labels: Second Review Required 👓, Tweak

#326 Restores AI Features
  baystation12.dme
  code/game/machinery/_machines_base/machinery.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm
  code/modules/nano/interaction/default.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/computers/sensors.dm
  html/changelogs/evenindeathistillserve-PR-326.yml
  nano/templates/helm.tmpl
  nano/templates/nav.tmpl
  nano/templates/shipsensors.tmpl
Labels: Feature

#329 Skirts and skirt accessories
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/under/corporate.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/skirts.dm
  html/changelogs/superhats-PR-329.yml
  icons/mob/onmob/onmob_under.dmi
  icons/mob/onmob/onmob_under_corporate.dmi
  icons/obj/clothing/obj_under.dmi
  modular_boh/icon/mob/onmob_under_solgov.dmi
  modular_boh/icon/obj/obj_under_solgov.dmi
Labels: Second Review Required 👓, Sprites

#331 Ports combi-knife extended functionality
  code/game/objects/items/weapons/material/swiss.dm
  html/changelogs/embershinori-PR-331.yml
Labels: Feature, Review Required 👓

#333 New boombox
  code/datums/supplypacks/nonessent.dm
  code/game/objects/items/devices/boombox.dm
  html/changelogs/evenindeathistillserve-PR-333.yml
  icons/mob/onmob/items/lefthand.dmi
  icons/mob/onmob/items/righthand.dmi
  icons/obj/boombox.dmi
Labels: Sprites, Tweak
